### ISSUE TITLE
[Feature Request] Provide `ScrollbarShow`, `ScrollbarHide` commands or similar

### ISSUE THREAD

**Issue by tbung** [petertriho/nvim-scrollbar#10]
It would be great to add commands to enable/disable the scrollbar on demand. This could be named show/hide or enable/disable or even just toggle.

This might also solve #7 as people can then just create autocommands to enable/disable the scrollbar.

**Comment by petertriho** [comment]
Done, I probably should separate commands to toggle/show/hide the handle, specific marks, and specific handlers
