### ISSUE TITLE
Option to hide scroll bar in buffers that fit on screen

### ISSUE THREAD

**Issue by J-Fields** [petertriho/nvim-scrollbar#12]
I'd like the scroll bar to only be shown when I would need to scroll to see something that isn't on screen. This could probably be done with some clever configuration once #10 is implemented, but to me, this seems like a sensible option to bake in.

**Comment by petertriho** [comment]
This sounds like a good idea. Definitely a sensible option that should just be baked in

**Comment by J-Fields** [comment]
That'd be my preference - this is how VS Code behaves with the minimap disabled

**Comment by petertriho** [comment]
Done
