### ISSUE TITLE
Error in diff view

### ISSUE THREAD

**Issue by meijieru** [petertriho/nvim-scrollbar#13]
Lots of error when have diff view in fugitive as the following:
```
pretty-fold.nvim/lua/pretty-fold/init.lua:68: in function <...ack/packer/opt/pretty-fold.nvim/lua/pretty-fold/init.lua:61>
```

**Comment by meijieru** [comment]
It comes from another plugin.

**Comment by petertriho** [comment]
This is an issue with the plugin not working properly with folds https://github.com/petertriho/nvim-scrollbar/issues/11
