### ISSUE TITLE
Sometimes throwing an error if incorrect code is detected

### ISSUE THREAD

**Issue by vuki656** [petertriho/nvim-scrollbar#14]
Quite often when I'm changing some code and in the middle of the change when the code is broken, it throws a random error. 

It's not every time, just at some weird times.

Here it happens when I put 11.

Pretty much just enter the file, go to the line, go to insert at the beginning of the line, type 11, go to normal mode => throws an error.

![image](https://user-images.githubusercontent.com/8104698/148595628-a070ee80-7b4b-4401-8a9d-3fa0e50b5047.png)

Here is the code to try and repro:

```lua
-- Name: Scrollbar
-- Description: Scrollbar with diagnostics
-- Link: https://github.com/petertriho/nvim-scrollbar

local scrollbar = require("scrollbar")

local colors = require("utils.colors")

------------------------------------------------------------------------------------------
----------------------------------- CONFIG -----------------------------------------------
------------------------------------------------------------------------------------------

scrollbar.setup({
    excluded_filetypes = {
        "NvimTree",
        "alpha",
        "docker-term",
        "git-term",
    },
    handle = {
        color = colors.background_light,
    },
    marks = {
        Error = { text = { "▀" }, color = colors.red },
        Warn = { text = { "▀" }, color = colors.orange },
        Info = { text = { "▀" }, color = colors.blue },
        Hint = { text = { "▀" }, color = colors.yellow },
        Misc = { text = { "▀" }, color = colors.green },
    },
})
```

**Comment by petertriho** [comment]
I can't seem to reproduce this. Can you try setup without any args? Just `scrollbar.setup()`

I'm thinking it could be either the config isn't being merged properly or color needs to be a specific format 

![image](https://user-images.githubusercontent.com/7420227/148630509-cef28d2e-78cd-468b-939f-af64e189e5e6.png)

**Comment by vuki656** [comment]
Managed to dig some crumbs. 

Here is the log from when it happens
![image](https://user-images.githubusercontent.com/8104698/148643191-5791392e-5cf6-4bf1-8d58-dc4d0b0fbe26.png)

I logged `handle_opts` in `init.lua` on line 121 like so

```lua
if handle_opts.virt_text[1][1] ~= "" and handle_opts.virt_text[1][1] ~= " " then
    print(vim.inspect(handle_opts))
end
```

I tried commenting out the config and still happens sometimes.

**Comment by vuki656** [comment]
Also, colors are in hex format like so

```lua
return {
    transparent = "#333840",
    background = "#282c34",
    background_light = "#3C4048",
    green = "#89ca78",
    purple = "#d55fde",
    yellow = "#e5c07b",
    blue = "#61afef",
    white = "#a5afbe",
    orange = "#d19a66",
    red = "#ef596f",
    grey = "#5c6370",
    grey_light = "#3e4452",
    grey_lighter = "#2c323c",
}
```

**Comment by petertriho** [comment]
Ok I see the issue, which neovim version are you on? Output of `nvim --version`

**Comment by vuki656** [comment]
I'm running nightly, currently on `NVIM v0.7.0-dev+844-gb43575545`

**Comment by petertriho** [comment]
I think having single mark text was breaking things. Just added a commit that may fix the issue that seems to be related to this.

```
marks = {
        Error = { text = { "▀" }, color = colors.red },
        Warn = { text = { "▀" }, color = colors.orange },
        Info = { text = { "▀" }, color = colors.blue },
        Hint = { text = { "▀" }, color = colors.yellow },
        Misc = { text = { "▀" }, color = colors.green },
    },
```

**Comment by vuki656** [comment]
Seems fixed, will report back if anything pops up.

Unrelated but for some reason the plugin removes my terminal cursor color or makes it transparent not sure. Take a look:
![Peek 2022-01-08 14-51](https://user-images.githubusercontent.com/8104698/148646779-bba92360-14ae-47cf-9adc-a19b14533aa7.gif)

**Comment by petertriho** [comment]
Is that using the neovim term? Maybe it has something to do with the "TermEnter" autocmd (required for terminal scrollbar)

**Comment by vuki656** [comment]
Yup, with the help of https://github.com/akinsho/toggleterm.nvim

**Comment by vuki656** [comment]
> Is that using the neovim term? Maybe it has something to do with the "TermEnter" autocmd (required for terminal scrollbar)

Just tried removing it and it seems to be the cuplrit.

**Comment by vuki656** [comment]
Been using it for a while now and nothing popped up so it seems it's fixed. I'll open another issue for the terminal.
