### ISSUE TITLE
Clear annotations contributed by `nvim-hlslens` when `:noh` is executed

### ISSUE THREAD

**Issue by J-Fields** [petertriho/nvim-scrollbar#15]
Not sure if this needs to be implemented on your side, his side, or in my config, but I think this should work out of the box.

**Comment by J-Fields** [comment]
Ah, it does - need to make sure `:noh<CR>` is called by your remap, NOT `<Cmd>noh<CR>`

**Comment by petertriho** [comment]
Yep, it's the same as hlslens' implementation, requiring `:nohl<CR>` instead of `<Cmd>nohl<CR>` to be mapped

https://github.com/kevinhwang91/nvim-hlslens#stop-hlslens
