### ISSUE TITLE
Set highlights on ColorScheme autocmd

### ISSUE THREAD

**Issue by jemag** [petertriho/nvim-scrollbar#16]
It seems that currently highlights are implemented just on setup and not with the ColorScheme autocmd. This means that they are likely to get cleared by most colorscheme.

For example, this is your highlights cleared (compared to non cleared highlights from other plugins above and below): 

![image](https://user-images.githubusercontent.com/7985687/148630548-6b5b918c-f063-4a3f-8a9e-e569d1195bc1.png)

As an implementation example, this is how it is done in nvim-notify
```lua
vim.cmd([[
  augroup NvimNotifyRefreshHighlights
    autocmd!
    autocmd ColorScheme * lua require('notify.config.highlights').setup()
  augroup END
]])

```

When highlights are cleared, even if the scrollbar renders, it might not show up in the terminal.

**Comment by petertriho** [comment]
Thank you, I'll implement a fix for this
