### ISSUE TITLE
Add "handler" for cursor position

### ISSUE THREAD

**Issue by J-Fields** [petertriho/nvim-scrollbar#17]
I find it helpful to have the cursor displayed as a mark on the scrollbar (as VS Code does it), so I have an idea of exactly where it is in relation to the more interesting marks

**Comment by crisidev** [comment]
I have done it using a custom handler like this one: 

```lua
    require("scrollbar.handlers").register("current_position", function(bufnr)
        local pos = vim.api.nvim_win_get_cursor(0)

        return {
            { line = pos[1], text = "x", type = "Misc" },
        }
    end)
```

**Comment by petertriho** [comment]
Sorry this so long, added!
