### ISSUE TITLE
[Feature Request] Create API and clear interface to add new mark handlers

### ISSUE THREAD

**Issue by tbung** [petertriho/nvim-scrollbar#19]
**Is your feature request related to a problem? Please describe.**
Since there are some issues now with people requesting different marks it might be a good idea to just provide a general api to register a new handler so people can extend the plugin in an easy fashion. Builtin handlers could then be just implemented on top of this api.

**Describe the solution you'd like**
Some restructuring of the code with a general handler interface to make adding handlers easy and a function or config option to register new handlers.

**Describe alternatives you've considered**
An alternative would be to add every requested handler into the project, which might exclude niche handlers that are out of scope or bloat the plugin.

**Additional context**
This relates to #2 and #17

**Comment by petertriho** [comment]
This is a great idea.

Could probably put some of this info into a wiki and, eventually, move this into some kind of org repo with separate plugins/modules for each handler.

At the moment, it should be pretty simple to add more handlers. Pretty much all marks go into `vim.b.scrollbar_marks` buffer variable. Each handler should use its own key.

E.g.

```
local my_marks = {
    { line = 1, text = "-", type = "Misc" }
}
local utils = require("scrollbar.utils")
local scrollbar_marks = utils.get_scrollbar_marks(bufnr)
scrollbar_marks.my_marks = my_marks
utils.set_scrollbar_marks(bufnr, scrollbar_marks)
require("scrollbar").render()
```

**Comment by tbung** [comment]
I just started to implement a generic register function that adds some abstraction over this boiler plate to eg just register a function that returns marks for a buffer, will probably have a draft pr ready later today.

I'll probably implement showing text marks on top of this while I'm at it and submit it in a separate pr.
