### ISSUE TITLE
Change the width of the scrollbar handle

### ISSUE THREAD

**Issue by nyngwang** [petertriho/nvim-scrollbar#28]
**Is your feature request related to a problem? Please describe.**
As title

**Describe the solution you'd like**
An option in the setup to setup the width of the handle

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by petertriho** [comment]
With the current implementation, widths are limited to the size of text characters. What you can do is increase the handle text to two space characters
E.g.
```
require("scrollbar").setup({
    handle = {
        text = "   ",
    },
    marks = {
        Search = { text = { "--", "==" } },
        Error = { text = { "--", "==" } },
        Warn = { text = { "--", "==" } },
        Info = { text = { "--", "==" } },
        Hint = { text = { "--", "==" } },
        Misc = { text = { "--", "==" } },
    }
})

```

**Comment by nyngwang** [comment]
This resolves my problem :) Thank you~

**Comment by kaykhan** [comment]
How do you also increase thickness of the dot?
