### ISSUE TITLE
Which plugin you usef in the DEMO to preview the color code?

### ISSUE THREAD

**Issue by nyngwang** [petertriho/nvim-scrollbar#29]
As title.

**Comment by petertriho** [comment]
https://github.com/RRethy/vim-hexokinase is what I'm using now but needs `golang` to build

I was using https://github.com/norcalli/nvim-colorizer.lua previously but it had too many bugs/poor performance.

**Comment by nyngwang** [comment]
@petertriho Thanks :) I'm using the same now. Yup the author of the latter one seems to be too busy to maintain it (last update time 2years ago.)
