### ISSUE TITLE
Better Default Colour

### ISSUE THREAD

**Issue by axieax** [petertriho/nvim-scrollbar#35]
**Is your feature request related to a problem? Please describe.**

The scrollbar being white tends to stick out from most themes, and customising for several different themes doesn't seem very friendly. 

**Describe the solution you'd like**

The default highlight group for ScrollBarHandle links to CursorLine (same as the example used in the README for TokyoNight). Perhaps even Diagnostic mark colours should link to the default Diagnostic* highlight groups as well! This makes it more consistent to individual ColorSchemes :)

**Describe alternatives you've considered**

Alternative solutions include manually finding and setting the colours by theme colour API's (as in the README), adding a custom highlight group override to every single theme configuration, or using an autocmd if this is not supported.

**Additional context**

**Comment by petertriho** [comment]
Sorry for taking so long, I've added "better" defaults (using existing highlights)
