### ISSUE TITLE
Error: bad argument #2 to 'to_hex_color' (number expected, got nil)

### ISSUE THREAD

**Issue by hexh250786313** [petertriho/nvim-scrollbar#36]
**Describe the bug**
- Error message occurs when enter neovim
- Screenshot:
   ![image](https://user-images.githubusercontent.com/26080416/153756406-307d6214-1237-4838-a181-26b0e17fed89.png)

**To Reproduce**
- Enter Neovim

**Expected behavior**
No error message.

**Version Info (please complete the following information):**
```
NVIM v0.7.0-dev+926-g6006e15e7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Config**
```lua
require("scrollbar").setup({})

```

**Comment by mcauley-penney** [comment]
The [conditional on line 57](https://github.com/petertriho/nvim-scrollbar/blob/b05b20a57e2341ad8a9a9a9b53a2ec4a3d677871/lua/scrollbar/utils.lua#L57) appears to not be catching when `type_color` is not `nil`. Changing the conditional to `if type_color ~= nil` fixes it for me. I don't really know why; I'm not learned enough in Lua to know the difference in this situation but I'm currently trying to wrap my head around it.

**Comment by yasudanaoya** [comment]
thx!
When I updated it, the error was fixed!

**Comment by hexh250786313** [comment]
https://github.com/petertriho/nvim-scrollbar/commit/16c5147864254af3ea436bbcfde3f85fd8253943 works for me. Issue closed. 

@petertriho
