### ISSUE TITLE
Cause serious lagging on large files (>10,000 lines)

### ISSUE THREAD

**Issue by nyngwang** [petertriho/nvim-scrollbar#45]
**Describe the bug**
As title.

**To Reproduce**
Just open a file with lines > 10,000.

**Expected behavior**
smooth scroll

**Screenshots**

**Version Info (please complete the following information):**
```
NVIM v0.8.0-dev+67-g0d41c4dee
Build type: Release
LuaJIT 2.1.0-beta3
```

**Additional context**

**Comment by petertriho** [comment]
Looks like the folds handling logic is causing issues in large files. I recommend you set folds = 1000 (or false if you don't use folds)

Let me know if this fixes things for you

**Comment by nyngwang** [comment]
I did use folding but I actually don't understand it very much. I'm using these options:

```lua
vim.cmd([[
  augroup MyStart
    au!
    au BufEnter,CursorHold * checktime
    au BufWinEnter * normal! zR
  augroup END
]])
vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'
function _G.my_custom_folding()
  return vim.fn.getline(vim.v.foldstart) .. ' ... ' .. vim.fn.getline(vim.v.foldend):gsub("^%s*", "")
end
vim.opt.fillchars:append({ fold = ' ' })
vim.opt.foldtext = 'v:lua.my_custom_folding()'
```

But yes, I'm trying your recommendation right now, wait a second!

**Comment by nyngwang** [comment]
What does `folds = 1000` mean btw?

**Comment by petertriho** [comment]
`folds = 1000` means that fold detection is disabled in files with lines > 1000

**Comment by YuanYuYuan** [comment]
Hi, @petertriho, I had the same bug of severe lagging on large files.

**To Reproduce**

1. Use neovim with a clean setting (fold disable) to open a LARGE_FILE (over 200 MiB in my test).

```bash
nvim -u clean.vim LARGE_FILE
```

_clean.vim_

```vim
set rtp=$VIMRUNTIME
```

After the buffer is loaded, the page scrolling in neovim is smooth.

2. Load the `nvim-scrollbar` plugin in neovim.

```vim
:lua require('scrollbar').setup()
```

Now we can observe the lag occurrence while scrolling.


**Version Info (please complete the following information):**


```bash
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by petertriho** [comment]
You'll need to disable the folds detection feature 
`lua require('scrollbar').setup({ folds = false })`

**Comment by YuanYuYuan** [comment]
Thanks for your kindly reply! I thought I turned off the fold function in neovim before since I had checked the same test with `:set nofoldenable`. But it seems that we need to disable the fold explicitly on the config of nvim-scrollbar. Anyway, this resolves the issue. Thanks!
