### ISSUE TITLE
works incorrectly with nvim-cmp

### ISSUE THREAD

**Issue by qixiao986** [petertriho/nvim-scrollbar#46]
**Describe the bug**
use  nvim-cmp autocompletion, the first placeholder automatically changed to zj.

**To Reproduce**
1. use nvim-cmp autocompletion, choose one item with placeholder.
2. the first placeholder automatically changed to zj.

**Expected behavior**
the first placeholder should remain same.

**Screenshots**
![output](https://user-images.githubusercontent.com/3962171/166174207-48a598f4-38dc-4de7-beab-feecd7b7fbcd.gif)

**Version Info (please complete the following information):**
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

```

**Comment by petertriho** [comment]
Reverted a change I made recently. That should fix this issue

**Comment by qixiao986** [comment]
> @qixiao986 Reverted a change I made recently. That should fix this issue
the issue fixed. 😄
