### ISSUE TITLE
Search tags do not disappear

### ISSUE THREAD

**Issue by fgheng** [petertriho/nvim-scrollbar#47]
**Describe the bug**
I map <backspace> to <cmd>nohls<cr>, but while I press backspace, the search tags still exists on the scrollbar.

**Screenshots**
search
![image](https://user-images.githubusercontent.com/50551377/166406275-c58c3819-22f1-4ebd-9d33-39aed2c3a8de.png)
press backspace
![image](https://user-images.githubusercontent.com/50551377/166406297-943bef83-8e59-46e6-8095-27c4abf72109.png)

**Version Info (please complete the following information):**
NVIM v0.8.0-dev+95-g07660193a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by petertriho** [comment]
Only clears for current buffer, change this to clear for all buffers

**Comment by petertriho** [comment]
@fgheng that should fix the issue

**Comment by fgheng** [comment]
thank you very much, I used command `:nohlsearch`, tags were cleared, but used the map key, nothing occured.

**Comment by petertriho** [comment]
What do you have the key mapped to? It needs to be `:nohlsearch` or `:nohl` as well

**Comment by fgheng** [comment]
Hello, I mapped to `backspace` 
![image](https://user-images.githubusercontent.com/50551377/166644104-a3db4591-35fb-497d-8a79-81735df03117.png)

**Comment by petertriho** [comment]
You need to change it `map('n', '<Backspace>', ':nohl<cr>', opts)
