### ISSUE TITLE
[Bug]: Editing a .h file makes nvim lag

### ISSUE THREAD

**Issue by LuKaS0473** [petertriho/nvim-scrollbar#49]
**Describe the bug**
When I edit an .h file and scroll down, nvim is extremely laggy. I then tested all the plugins and found out that the scrollbar plugin is the problem. I have the following code in my "init.lua" file of nvim: 

local colors = require("tokyonight.colors").setup()

require("scrollbar").setup({
handle = {
&nbsp; color = colors.bg_highlight,
},
&nbsp;    marks = {
&nbsp;&nbsp;        Search = { colour = colors.orange },
&nbsp;&nbsp;       Error = { colour = colors.error },
&nbsp;&nbsp;        Warn = { colour = colors.warning },
&nbsp;&nbsp;         Info = { colour = colors.info },
&nbsp;&nbsp;         Hint = { colour = colors.hint },
&nbsp;&nbsp;        Misc = { colour = colors.purple },
&nbsp;    }
})

As soon as I comment out this part of the code and restart nvim. Everything is lag-free.

**To Reproduce**
1. open an .h file (e.g. .config/dwm/config.h)
2. scroll down to produce lag
3. comment out the above code (.config/nvim/init.lua)
4. restart nvim
5. open the .h file again and see the difference

**Expected behavior**
If the problem is not with me, then it should lag with the program code when you scroll down and if you comment out the program code from above, then nvim should run normally again when editing the .h file.

**Version:**
Nvim v0.7.0

**Comment by petertriho** [comment]
Try
```lua
require("scrollbar").setup({
	folds = false,
	handle = {
		color = colors.bg_highlight,
	},
	marks = {
		Search = { colour = colors.orange },
		Error = { colour = colors.error },
		Warn = { colour = colors.warning },
		Info = { colour = colors.info },
		Hint = { colour = colors.hint },
		Misc = { colour = colors.purple },
	}
})
```

**Comment by LuKaS0473** [comment]
@petertriho it is still the same.

**Comment by petertriho** [comment]
Does the file have a lot of diagnostics? I've tested this on a 200k lines file and worked fine.

**Comment by LuKaS0473** [comment]
No I don't think so. Here is my small init.lua file:
[init.txt](https://github.com/petertriho/nvim-scrollbar/files/8678897/init.txt)

**Comment by petertriho** [comment]
Could try this: 
`require("scrollbar").setup({
	folds = false,
	handle = {
		color = colors.bg_highlight,
	},
	marks = {
		Search = { colour = colors.orange },
		Error = { colour = colors.error },
		Warn = { colour = colors.warning },
		Info = { colour = colors.info },
		Hint = { colour = colors.hint },
		Misc = { colour = colors.purple },
	},
	handlers = {
		diagnostics = false
	}
})`

If that doesn't help. I'm not too sure what will. I do have plans to rewrite this to throttle the rendering + split out the rendering of individual marks + handle.

**Comment by LuKaS0473** [comment]
It got a little better but it still lags. Thanks for the help anyway
