### ISSUE TITLE
Haha, do you know what happend about this

### ISSUE THREAD

**Issue by fgheng** [petertriho/nvim-scrollbar#51]
**Describe the bug**
look at this gif
![Peek 2022-05-16 00-23](https://user-images.githubusercontent.com/50551377/168483177-29d74cad-f48d-4724-91af-2c383e4a895c.gif)

**Comment by petertriho** [comment]
It's a limitation with the buffer specific implementation at the moment https://github.com/petertriho/nvim-scrollbar/issues/6

I plan to work on a new implementation that should fix this but in the meantime there's no fix for this
