### ISSUE TITLE
Hello, when there is an error in the code, the scroll bar will prompt. When I fix the code, it is still there. How can I make it disappear?

### ISSUE THREAD

**Issue by Wjinlei** [petertriho/nvim-scrollbar#52]
**Describe the bug**
Hello, when there is an error in the code, the scroll bar will prompt. When I fix the code, it is still there. How can I make it disappear?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - `nvim --version`

**Additional context**

**Comment by petertriho** [comment]
Is this with coc or native neovim lsp?

**Comment by Wjinlei** [comment]
> 这是 coc 还是枣 neovim lsp？

nvim-cmp

**Comment by joesitton** [comment]
Also experiencing this

Before:
![image](https://user-images.githubusercontent.com/5003990/173432333-8ba99320-733e-4732-bebb-b3d0d5f73fcb.png)

After:
![image](https://user-images.githubusercontent.com/5003990/173432393-410944b7-83ee-4ac5-9705-2e466a98ba46.png)

After fix:
![image](https://user-images.githubusercontent.com/5003990/173432507-8100a24c-8e17-45a1-bee4-c0f19e5eaa3d.png)

"Error" diagnostic line is still in the scrollbar.
