### ISSUE TITLE
Bug: Having more than one Custom Handler disables all but last handling

### ISSUE THREAD

**Issue by chrisgrieser** [petertriho/nvim-scrollbar#66]
**Describe the bug**
I played a bit with custom Handlers, and I noticed that when I register more than one custom handler, all but the last one seem to be disabled.

**To Reproduce**
create two handlers with `require("scrollbar.handlers").register("foo", function(bufnr) ... end`

**Expected behavior**
All custom handlers should work

**Version Info (please complete the following information):**
```
macOS 13.0.1 (M1)
neovim 0.8.0 (homebrew)
```

**Comment by petertriho** [comment]
Fixed 😄
