### ISSUE TITLE
Make handle bar optional

### ISSUE THREAD

**Issue by jotacosta-fb** [petertriho/nvim-scrollbar#67]
I use nvim-scrollbar to see LspErrors and searches. I would love to have the option to turn off the handle entirely. Effectively, I do this today by matching the handle background to neovim background:

```
hi scrollbarHandle guibg=none guifg=none
```

But what I would like to have is just a config to turn off handle (and not just cursor).
```
 handlers = {
        handle = false,
        cursor = false,
        diagnostic = true,
        gitsigns = false,
        search = true, 
    },
```

**Comment by petertriho** [comment]
Done
```
 handlers = {
        handle = false,
    },
```
should do the trick
