### ISSUE TITLE
Scrollbar glitch

### ISSUE THREAD

**Issue by rgnkn** [petertriho/nvim-scrollbar#74]
Since commit "perf: throttle rendering #49 #68 #72" (a377bb6705a798febc6c545a4494f366ab0a9648) the scrollbar is very weirdly jumping up and down (no smooth scrolling) when scrolling around in a file.

Before that commit:

[Screencast from 07.12.2022 22:41:49.webm](https://user-images.githubusercontent.com/17874137/206302849-44e83a19-0373-40b8-b75a-024f14818204.webm)

After that commit:

[Screencast from 07.12.2022 22:39:20.webm](https://user-images.githubusercontent.com/17874137/206302893-236a2901-5f0a-4926-9e32-415a0eecd47e.webm)

 - `nvim --version` = NVIM v0.9.0-dev

**Comment by petertriho** [comment]
This has always been an issue. You can try reducing `throttle_ms` (or set to 0) to reduce the jumpiness. I'm working on a proper fix for this.

**Comment by rgnkn** [comment]
Thumbs up: That was quick!

Setting it to `0` made the trick. You might want to mention this in your `README.md`.

BTW: Thanks for this superb plugin.

**Comment by petertriho** [comment]
Ok, I added a better fix, should not need to set `throttle_ms` to 0 now

**Comment by rgnkn** [comment]
Yep, even better. I can confirm that it works my end (without setting `throttle_ms`).
