### ISSUE TITLE
Mark Priority

### ISSUE THREAD

**Issue by rgnkn** [petertriho/nvim-scrollbar#75]
I have a question that might be already somehow inside but I couldn't find it.

I use your plugin both with the `gitsigns` and the `nvim-hlslens` feature. Everything is fine, but I'd like that in case that there are several potential marks could be set that `Errors` have a higher priority to be shown than `nvim-hlslens` marks (this is an example, so, I don't know the exact ordering for all types of marks, but this one is for sure). Currently, at least in my config the `nvim-hlslens` marks seem to have a higher priority.

Is there any option to set the priority of marks or can you envision something with my setup that could help me with regards to this?

**Comment by petertriho** [comment]
```lua
require("scrollbar").setup({
    marks = {
        Cursor = {
            priority = 0,
        },
        Search = {
            priority = 1,
        },
        Error = {
            priority = 2,
        },
        Warn = {
            priority = 3,
        },
        Info = {
            priority = 4,
        },
        Hint = {
            priority = 5,
        },
        Misc = {
            priority = 6,
        },
        GitAdd = {
            priority = 7,
        },
        GitChange = {
            priority = 7,
        },
        GitDelete = {
            priority = 7,
        },
    },
})
```
That's the current priority list. smaller number = higher priority

If you wish to set Errors to have a higher priority, you can do something like (swap their priorities)

```lua
require("scrollbar").setup({
    marks = {
        Search = {
            priority = 2,
        },
        Error = {
            priority = 1,
        },
})
```

**Comment by rgnkn** [comment]
Thx again.
