### ISSUE TITLE
[Bug] Scrollbar disappears from split

### ISSUE THREAD

**Issue by levouh** [petertriho/nvim-scrollbar#8]
# Configuration

```lua
require("scrollbar").setup({
  handlers = {
    diagnostic = true,
    search = false,
  },
})
```

# Version

`NVIM v0.7.0-dev+839-g09d270bce`

# Behavior & reproduction

1. Open a buffer
2. Vertically split that buffer
3. Change focus between the two splits
4. Observe the below behavior:

https://user-images.githubusercontent.com/31262046/148561061-cf173b2f-18a8-46e2-abab-f2ec2e65f52b.mp4

# Expected behavior

Scrollbar state should remain exactly the same when switching windows.

**Comment by petertriho** [comment]
This appears an issue when the same buffer appears in multiple windows (different buffers in different windows doesn't seem to have the same issue). I'll need to investigate further

**Comment by levouh** [comment]
Agreed, it is just going out of view in the second window. Closing.
