### ISSUE TITLE
Question: Check is scrollbar is active

### ISSUE THREAD

**Issue by tummetott** [petertriho/nvim-scrollbar#85]
Hello, 

i'm currently implementing a custom `foldtext` function and I'm wondering if there is way to check if the scrollbar is enabled or not. I like disabeling the scrollbar from time to time but then i'd like to dynamically adjust the screen width inside my foldtext function. 

Thank you

**Comment by petertriho** [comment]
You can probably check `require("scrollbar.config").get().show == true`

**Comment by tummetott** [comment]
> You can probably check `require("scrollbar.config").get().show == true`

That solves the problem perfectly. Thank you. No need for an autocmd.

❤️
