### ISSUE TITLE
[Help] How to configure scrollbar like demo GIF

### ISSUE THREAD

**Issue by gbroques** [petertriho/nvim-scrollbar#93]
Can you provide an example configuration for how to configure the scrollbar as seen in the demo GIF?

I installed `folke/tokyonight.nvim` as my theme, and then copied the [configuration from the README](https://github.com/petertriho/nvim-scrollbar#example-config-with-tokyonightnvim-colors):
```lua
local colors = require("tokyonight.colors").setup()

require("scrollbar").setup({
    handle = {
        color = colors.bg_highlight,
    },
    marks = {
        Search = { color = colors.orange },
        Error = { color = colors.error },
        Warn = { color = colors.warning },
        Info = { color = colors.info },
        Hint = { color = colors.hint },
        Misc = { color = colors.purple },
    }
})
```

However, this doesn't seem to be the configuration used in the demo.

I still have:
* a dot for the cursor mark
* 3 vertical dashed lines┆for git add / git change
* and other things which aren't like the demo.

Thank you for working on this great plugin! It's very helpful to have a sense of how big the file is.

![Demo GIF](https://raw.githubusercontent.com/petertriho/nvim-scrollbar/main/assets/diagnostics.gif)

**Comment by petertriho** [comment]
That gif was made when those features weren't added.
You can disable those features using through `handlers`

```lua
local colors = require("tokyonight.colors").setup()

require("scrollbar").setup({
    handle = {
        color = colors.bg_highlight,
    },
    marks = {
        Search = { color = colors.orange },
        Error = { color = colors.error },
        Warn = { color = colors.warning },
        Info = { color = colors.info },
        Hint = { color = colors.hint },
        Misc = { color = colors.purple },
		GitAdd = { text = "│" }, -- or another desired icon
        GitChange = { text = "│" },
        GitDelete = { text = "│" },
    },
	handlers = {
        cursor = false,
        diagnostic = true,
        gitsigns = false,
        handle = true,
        search = false,
        ale = false,
    },
})
```

**Comment by gbroques** [comment]
Thank you for your response @petertriho and work on this plugin!
