### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by Etholacto** [petertriho/nvim-scrollbar#95]
**Describe the bug**
seemingly an error when trying a fresh install of scrollbar, gives a warning about a missing equal sign near line 100 of the utils.lua, upon trying a manual fix (tried adding = to highlight %s like the other vars) it threw another error

**To Reproduce**
1. fresh install of scrollbar
2. fresh install of tokyonight (without configs set, im using a different theme, but still want tokyonight colors)
3. copy paste deafult configs into a scrollbar.lua file under the after directory
4. Change only the color values in the various marks and in the handle
5. save and source the file gives the error (or close and reopen of neovim)

**Expected behavior**
obviously not an error that appears upon restarting neovim 

**Screenshots**
![image](https://user-images.githubusercontent.com/119801155/234269942-545d9913-53ab-4009-a9c8-5dc2e931c103.png)

**Version Info (please complete the following information):**
 - NVIM v0.8.3
- Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Additional context**

**Comment by petertriho** [comment]
Under `marks.Search`, `color = colors.orange` not the table `color = { color = colors.orange }

**Comment by Etholacto** [comment]
Thank you
