### ISSUE TITLE
Question: How can I disable nvim-scrollbar on nvim-cmp?

### ISSUE THREAD

**Issue by Zeioth** [petertriho/nvim-scrollbar#97]
When both nvim-scrollbar and nvim-cmp are present at the same time, two scrollbars are displayed on the completion menu. How can I avoid this?
![screenshot_2023-05-23_23-49-00_105821632](https://github.com/petertriho/nvim-scrollbar/assets/3357792/40163d75-0a81-4b09-ba1c-a29aaff32d62)

**Comment by Zeioth** [comment]
Possibly related to #39

**Comment by petertriho** [comment]
I've added `cmp_menu` and `cmp_doc` filetypes to the default config to not show them

**Comment by Zeioth** [comment]
That indeed fixed the issue thank you!!!

**Comment by tummetott** [comment]
For future reference: It's `cmp_docs` and not `cmp_doc`

**Comment by mirql** [comment]
Hello! still visible in "blink.cmp"

**Comment by mirql** [comment]
this opts fixes the issue with `blink.cmp`

```lua
{
    excluded_buftypes = {
        "nofile",
        "popup",
        "noice",
      },
      excluded_filetypes = {
        "popup",
        "noice",
        "blink-cmp-menu",
        "blink-cmp-signature",
        "blink-cmp-documentation",
      },
}
```
